07 db
Maryna-Z/AT_ISsoft pull request #6
Opened 2021-02-11 19:56 UTC by Maryna-Z

Add DB functionality

2021-03-25 15:14 UTC, artemmoroz requested changes

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/dao/src/main/java/com/marina/dao/DBConnection/DatabaseConnection.java
> +package com.marina.dao.DBConnection;
wrong package name

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/dao/src/main/java/com/marina/dao/DBConnection/DatabaseConnection.java
> +    private static String path = "c:/Users/user/Java/AT_ISsoft/AT_ISsoft/OnlineStore/dao/src/main/resources/db.properties";
u can not use any absolute path in your apps

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/dao/src/main/java/com/marina/dao/DBConnection/DatabaseConnection.java
> +        if (uniqueInstance == null) {
you need smthing for synchronization your instance

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/dao/src/main/java/com/marina/dao/commonDAO/CategoriesDAO.java
> +            throwables.printStackTrace();
now a very good option just to print stacktrace

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/dao/src/main/java/com/marina/dao/commonDAO/CategoriesDAO.java
> +    CommonDAO commonDAO = new CommonDAO();
inheritance?

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/dao/src/main/java/com/marina/dao/commonDAO/ProductsDAO.java
> +        Connection connection = null;
very similar class to categoryDAO

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/domain/src/main/java/com/marina/entities/Product.java
> +    private int productID;
you should not merge domain model and db model classes

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/domain/src/main/java/com/marina/entities/Product.java
> +    private int categoryID;
and also naming conventions (camelCase)

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/store/src/main/java/com/marina/utility/Utils.java
> +        System.out.println("Input product id: ");
text in service method (imp)

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/store/src/main/java/com/marina/utility/Utils.java
> +        return (int)(min + Math.random() * max);
you can use faker for that (imp)

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/store/src/main/java/com/marina/services/impl/BasicProductPublisher.java
> +        List<Product> products = new ArrayList<>();
discuss

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/domain/src/main/java/com/marina/entities/Product.java
> +    private int productID;
lib: bean copy utils, objects merge

2021-03-25 15:14 UTC, artemmoroz commented on OnlineStore/store/src/main/java/com/marina/services/impl/ReflectionPublisher.java
> +            int categoryID = clazz.getField("categoryID").getInt(o);
Category o = (Category) Class.forName(clazz.getName()).newInstance();
        categories.add(o);

2021-03-25 18:48 UTC, Maryna-Z commented on OnlineStore/dao/src/main/java/com/marina/dao/DBConnection/DatabaseConnection.java
> +package com.marina.dao.DBConnection;
fixed

2021-03-25 19:06 UTC, Maryna-Z commented on OnlineStore/dao/src/main/java/com/marina/dao/DBConnection/DatabaseConnection.java
> +    private static String path = "c:/Users/user/Java/AT_ISsoft/AT_ISsoft/OnlineStore/dao/src/main/resources/db.properties";
fixed

2021-03-25 19:06 UTC, Maryna-Z commented on OnlineStore/dao/src/main/java/com/marina/dao/DBConnection/DatabaseConnection.java
> +        if (uniqueInstance == null) {
fixed

2021-03-25 19:11 UTC, Maryna-Z commented on OnlineStore/dao/src/main/java/com/marina/dao/commonDAO/CategoriesDAO.java
> +    CommonDAO commonDAO = new CommonDAO();
fixed

2021-03-25 19:11 UTC, Maryna-Z commented on OnlineStore/dao/src/main/java/com/marina/dao/commonDAO/ProductsDAO.java
> +        Connection connection = null;
fixed

2021-03-25 20:16 UTC, Maryna-Z commented on OnlineStore/dao/src/main/java/com/marina/dao/commonDAO/CategoriesDAO.java
> +            throwables.printStackTrace();
fixed

2021-03-27 19:13 UTC, Maryna-Z commented on OnlineStore/domain/src/main/java/com/marina/entities/Product.java
> +    private int productID;
fixed

2021-03-27 19:13 UTC, Maryna-Z commented on OnlineStore/domain/src/main/java/com/marina/entities/Product.java
> +    private int categoryID;
fixed

2021-03-27 19:17 UTC, Maryna-Z commented on OnlineStore/store/src/main/java/com/marina/services/impl/BasicProductPublisher.java
> +        List<Product> products = new ArrayList<>();
impl

2021-03-28 18:30 UTC, Maryna-Z commented on OnlineStore/store/src/main/java/com/marina/services/impl/ReflectionPublisher.java
> +            int categoryID = clazz.getField("categoryID").getInt(o);
fixed

2021-03-29 08:23 UTC, artemmoroz approved these changes

2021-03-29 08:23 UTC, artemmoroz commented on OnlineStore/data/src/main/java/com/marina/dao/CategoriesDAO.java
> +    public void completeStatement(PreparedStatement statement, List<Category> list) {
it is better to thow ex (e/g unssoported operation, or similar) or implement method. Just not leave him empty)

2021-03-29 08:23 UTC, merged